similarity-threshold = 10

# you can use .env file to set these env vars instead of here

[telegram]
# or use DUPFINDER_TELEGRAM_TOKEN env var
token = "your token"

[database]
url = "postgres://user:password@localhost:5432/dbname"
