log_level = "debug"
similarity_threshold = 20

# you can use .env file to set these env vars instead of here

[telegram]
# or use DUPFINDER_TELEGRAM_TOKEN env var
token = "your token"

[database]
# or use DUPFINDER_database_URL env var (automatically set by the nix flake)
url = "postgres://user:password@localhost:5432/dbname"
